export const GET_ALL_BOOKS_REQUEST = "GET_ALL_BOOKS_REQUEST";
export const GET_ALL_BOOKS_SUCCESS = "GET_ALL_BOOKS_SUCCESS";
export const GET_ALL_BOOKS_FAIL = "GET_ALL_BOOKS_FAIL";

export const GET_BOOK_DETAILS_REQUEST = "GET_BOOK_DETAILS_REQUEST";
export const GET_BOOK_DETAILS_SUCCESS = "GET_BOOK_DETAILS_SUCCESS";
export const GET_BOOK_DETAILS_FAIL = "GET_BOOK_DETAILS_FAIL";

export const GET_BOOKS_REC_SECTION_REQUEST = "GET_BOOKS_REC_SECTION_REQUEST";
export const GET_BOOKS_REC_SECTION_SUCCESS = "GET_BOOKS_REC_SECTION_SUCCESS";
export const GET_BOOKS_REC_SECTION_FAIL = "GET_BOOKS_REC_SECTION_FAIL";

export const GET_BOOKS_RANDOM_REQUEST = "GET_BOOKS_RANDOM_REQUEST";
export const GET_BOOKS_RANDOM_SUCCESS = "GET_BOOKS_RANDOM_SUCCESS";
export const GET_BOOKS_RANDOM_FAIL = "GET_BOOKS_RANDOM_FAIL";