export const GET_USERS_WISHLIST_REQUEST = "GET_USERS_WISHLIST_REQUEST";
export const GET_USERS_WISHLIST_SUCCESS = "GET_USERS_WISHLIST_SUCCESS";
export const GET_USERS_WISHLIST_FAIL = "GET_USERS_WISHLIST_FAIL";

export const ADD_BOOK_TO_WISHLIST_REQUEST = "ADD_BOOK_TO_WISHLIST_REQUEST";
export const ADD_BOOK_TO_WISHLIST_SUCCESS = "ADD_BOOK_TO_WISHLIST_SUCCESS";
export const ADD_BOOK_TO_WISHLIST_FAIL = "ADD_BOOK_TO_WISHLIST_FAIL";

export const REMOVE_BOOK_FROM_WISHLIST_REQUEST = "REMOVE_BOOK_FROM_WISHLIST_REQUEST";
export const REMOVE_BOOK_FROM_WISHLIST_SUCCESS = "REMOVE_BOOK_FROM_WISHLIST_SUCCESS";
export const REMOVE_BOOK_FROM_WISHLIST_FAIL = "REMOVE_BOOK_FROM_WISHLIST_FAIL";